//! whostty: app-side input handling — translate Win32 key events into the
//! terminal byte sequences to write back to the pty.
//!
//! Reference: ghostty `src/input.zig` + apprt key handling (strategy: port).
//! The actual encoding is delegated to libghostty-vt (`input.encodeKey`); this
//! module only maps Win32 virtual-key codes / modifier state into a
//! `vt.input.KeyEvent`. See PORTING.md.
const std = @import("std");
const vt = @import("ghostty-vt");

pub const KeyEvent = vt.input.KeyEvent;
pub const Key = vt.input.Key;
pub const Mods = vt.input.KeyMods;
pub const Options = vt.input.KeyEncodeOptions;

/// Win32 virtual-key codes we map to terminal keys. These are the
/// non-character keys (control, navigation, editing, function) whose bytes are
/// generated by libghostty-vt's encoder rather than arriving as text via
/// WM_CHAR. Values from the Win32 `VK_*` constants.
pub const vk = struct {
    pub const back: u32 = 0x08;
    pub const tab: u32 = 0x09;
    pub const enter: u32 = 0x0D;
    pub const escape: u32 = 0x1B;
    pub const page_up: u32 = 0x21; // VK_PRIOR
    pub const page_down: u32 = 0x22; // VK_NEXT
    pub const end: u32 = 0x23;
    pub const home: u32 = 0x24;
    pub const left: u32 = 0x25;
    pub const up: u32 = 0x26;
    pub const right: u32 = 0x27;
    pub const down: u32 = 0x28;
    pub const insert: u32 = 0x2D;
    pub const delete: u32 = 0x2E;
    pub const f1: u32 = 0x70;
    pub const f4: u32 = 0x73;
    pub const f12: u32 = 0x7B;
};

/// Whether an `Alt`-modified press of this virtual key (which Windows delivers
/// as WM_SYSKEYDOWN, not WM_KEYDOWN) should be sent to the shell rather than
/// handled by Windows. True for the navigation / arrow / function keys, which
/// have no character (WM_SYSCHAR) twin and don't touch the WM_CHAR-suppression
/// path. Excludes:
///   - `Alt+F4`, kept as the standard window-close shortcut;
///   - Enter/Tab/Backspace/Escape, whose Alt combos would post a WM_SYSCHAR and
///     desync the suppress-next-char flag (deferred with Alt-as-Meta, #82);
///   - everything else (Alt+letter, Alt+Space system menu, Alt alone), left to
///     Windows' default handling.
pub fn altSpecialToShell(code: u32) bool {
    if (code == vk.f4) return false; // Alt+F4 stays the window-close shortcut.
    return switch (code) {
        vk.left, vk.up, vk.right, vk.down => true,
        vk.home, vk.end, vk.page_up, vk.page_down, vk.insert, vk.delete => true,
        vk.f1...vk.f12 => true,
        else => false,
    };
}

/// Map a Win32 virtual-key code to a libghostty-vt `Key`. Returns
/// `.unidentified` for keys whose text comes from WM_CHAR instead (letters,
/// digits, punctuation), which the caller drops so they are not double-sent.
pub fn keyFromVk(code: u32) Key {
    return switch (code) {
        vk.back => .backspace,
        vk.tab => .tab,
        vk.enter => .enter,
        vk.escape => .escape,
        vk.page_up => .page_up,
        vk.page_down => .page_down,
        vk.end => .end,
        vk.home => .home,
        vk.left => .arrow_left,
        vk.up => .arrow_up,
        vk.right => .arrow_right,
        vk.down => .arrow_down,
        vk.insert => .insert,
        vk.delete => .delete,
        // F1..F12 are contiguous (0x70..0x7B); map to the contiguous f1..f12.
        vk.f1...vk.f12 => @enumFromInt(@intFromEnum(Key.f1) + @as(c_int, @intCast(code - vk.f1))),
        else => .unidentified,
    };
}

/// Build modifiers from individual key states (as read from GetKeyState).
pub fn mods(shift: bool, ctrl: bool, alt: bool) Mods {
    return .{ .shift = shift, .ctrl = ctrl, .alt = alt };
}

/// Encode a key event into terminal bytes, writing into `buf`. Returns the
/// written slice (may be empty if the event produces no bytes).
pub fn encode(buf: []u8, event: KeyEvent, opts: Options) ![]const u8 {
    var writer: std.Io.Writer = .fixed(buf);
    try vt.input.encodeKey(&writer, event, opts);
    return writer.buffered();
}

test "input: Enter encodes to CR" {
    var buf: [8]u8 = undefined;
    const out = try encode(&buf, .{ .key = .enter }, .{});
    try std.testing.expectEqualStrings("\r", out);
}

test "input: printable text passes through" {
    var buf: [8]u8 = undefined;
    const out = try encode(&buf, .{ .utf8 = "a", .unshifted_codepoint = 'a' }, .{});
    try std.testing.expectEqualStrings("a", out);
}

test "input: backspace and tab" {
    var buf: [8]u8 = undefined;
    const bs = try encode(&buf, .{ .key = .backspace }, .{});
    try std.testing.expect(bs.len >= 1);

    var buf2: [8]u8 = undefined;
    const tab = try encode(&buf2, .{ .key = .tab }, .{});
    try std.testing.expectEqualStrings("\t", tab);
}

test "input: vk mapping" {
    try std.testing.expectEqual(Key.enter, keyFromVk(vk.enter));
    try std.testing.expectEqual(Key.arrow_up, keyFromVk(vk.up));
    try std.testing.expectEqual(Key.unidentified, keyFromVk('A'));
}

test "input: arrow key produces an escape sequence" {
    var buf: [16]u8 = undefined;
    const out = try encode(&buf, .{ .key = .arrow_up }, .{});
    try std.testing.expect(out.len >= 2 and out[0] == 0x1b);
}

test "input: modified arrow keys encode the modifier" {
    var buf: [16]u8 = undefined;
    // xterm CSI 1 ; <mod> <final>, where mod = 1 + bitmask (shift=1, alt=2, ctrl=4).
    try std.testing.expectEqualStrings(
        "\x1b[1;5A",
        try encode(&buf, .{ .key = .arrow_up, .mods = .{ .ctrl = true } }, .{}),
    );
    try std.testing.expectEqualStrings(
        "\x1b[1;2A",
        try encode(&buf, .{ .key = .arrow_up, .mods = .{ .shift = true } }, .{}),
    );
    try std.testing.expectEqualStrings(
        "\x1b[1;3A",
        try encode(&buf, .{ .key = .arrow_up, .mods = .{ .alt = true } }, .{}),
    );
}

test "input: cursor-key application mode switches arrows to SS3" {
    var buf: [16]u8 = undefined;
    // DECCKM off -> CSI A; on -> SS3 A.
    try std.testing.expectEqualStrings("\x1b[A", try encode(&buf, .{ .key = .arrow_up }, .{}));
    try std.testing.expectEqualStrings(
        "\x1bOA",
        try encode(&buf, .{ .key = .arrow_up }, .{ .cursor_key_application = true }),
    );
}

test "input: shift+tab encodes back-tab" {
    var buf: [16]u8 = undefined;
    try std.testing.expectEqualStrings(
        "\x1b[Z",
        try encode(&buf, .{ .key = .tab, .mods = .{ .shift = true } }, .{}),
    );
}

test "input: altSpecialToShell selects nav/function keys but not F4 or letters" {
    // Sent to the shell under Alt (arrive as WM_SYSKEYDOWN).
    for ([_]u32{
        vk.left, vk.up, vk.right, vk.down,
        vk.home, vk.end, vk.page_up, vk.page_down,
        vk.insert, vk.delete, vk.f1, vk.f12,
    }) |c| try std.testing.expect(altSpecialToShell(c));

    // Left to Windows: Alt+F4 (close), Enter/Tab (suppress path), a letter.
    try std.testing.expect(!altSpecialToShell(vk.f4));
    try std.testing.expect(!altSpecialToShell(vk.enter));
    try std.testing.expect(!altSpecialToShell(vk.tab));
    try std.testing.expect(!altSpecialToShell('A'));
}

test "input: navigation and function keys map and encode" {
    try std.testing.expectEqual(Key.home, keyFromVk(vk.home));
    try std.testing.expectEqual(Key.end, keyFromVk(vk.end));
    try std.testing.expectEqual(Key.page_up, keyFromVk(vk.page_up));
    try std.testing.expectEqual(Key.page_down, keyFromVk(vk.page_down));
    try std.testing.expectEqual(Key.insert, keyFromVk(vk.insert));
    try std.testing.expectEqual(Key.delete, keyFromVk(vk.delete));
    try std.testing.expectEqual(Key.f1, keyFromVk(vk.f1));
    try std.testing.expectEqual(Key.f12, keyFromVk(vk.f12));
    try std.testing.expectEqual(Key.f5, keyFromVk(0x74));

    var buf: [16]u8 = undefined;
    // Each produces a non-empty escape sequence (exact bytes are the encoder's).
    for ([_]Key{ .home, .end, .page_up, .page_down, .insert, .delete, .f1, .f12 }) |k| {
        const out = try encode(&buf, .{ .key = k }, .{});
        try std.testing.expect(out.len >= 2 and out[0] == 0x1b);
    }
}
